using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Shapes;
using DesktopNMS.Core.Configuration;
using DesktopNMS.Core.Models;
using DesktopNMS.ViewModels;

namespace DesktopNMS.Views;

/// <summary>
/// The Dashboard tab: at-a-glance widgets laid out on a snapped grid. Widgets
/// are positioned in whole grid cells (<see cref="DashboardWidget.CellSize"/>
/// pixels each); dragging or resizing one over another displaces it straight
/// down (cascading to whatever that newly overlaps) rather than just being
/// blocked, so rearranging feels like reflowing a layout instead of picking a
/// careful gap to squeeze into.
/// </summary>
public partial class DashboardView : UserControl
{
    private Canvas? _widgetsCanvas;

    private DashboardWidgetViewModel? _draggingWidget;
    private Point _dragStartMousePosition;
    private int _dragOriginColumn;
    private int _dragOriginRow;

    private DashboardWidgetViewModel? _resizingWidget;
    private Point _resizeStartMousePosition;
    private int _resizeOriginColumnSpan;
    private int _resizeOriginRowSpan;

    public DashboardView()
    {
        InitializeComponent();
    }

    private void OnLoaded(object sender, RoutedEventArgs e)
    {
        if (DataContext is DashboardViewModel viewModel)
        {
            viewModel.Widgets.CollectionChanged -= OnWidgetsCollectionChanged;
            viewModel.Widgets.CollectionChanged += OnWidgetsCollectionChanged;
            viewModel.WidgetAdded -= OnWidgetAdded;
            viewModel.WidgetAdded += OnWidgetAdded;
        }

        UpdateCanvasExtent();
    }

    private void OnWidgetsCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e) => UpdateCanvasExtent();

    private void OnCanvasSizeChanged(object sender, SizeChangedEventArgs e) => UpdateCanvasExtent();

    /// <summary>
    /// Grows the canvas to whatever is bigger - the visible viewport, or the
    /// furthest extent of any widget - so dragging/growing a widget past the
    /// current view makes the canvas scrollable rather than clipping it, and
    /// shrinks back down (no further than the viewport) once nothing needs
    /// the extra room any more.
    /// </summary>
    private void UpdateCanvasExtent()
    {
        if (DataContext is not DashboardViewModel viewModel)
        {
            return;
        }

        var canvas = FindWidgetsCanvas();
        if (canvas is null)
        {
            return;
        }

        double contentWidth = 0;
        double contentHeight = 0;

        foreach (var widget in viewModel.Widgets)
        {
            contentWidth = Math.Max(contentWidth, (widget.Column + widget.ColumnSpan) * DashboardWidget.CellSize);
            contentHeight = Math.Max(contentHeight, (widget.Row + widget.RowSpan) * DashboardWidget.CellSize);
        }

        canvas.Width = Math.Max(CanvasScroll.ActualWidth, contentWidth);
        canvas.Height = Math.Max(CanvasScroll.ActualHeight, contentHeight);
    }

    /// <summary>
    /// The Canvas is generated by <c>WidgetsHost</c>'s <see cref="ItemsControl.ItemsPanel"/>
    /// template, so it has no code-behind field of its own - it must be found
    /// in the visual tree instead, once it exists (it may not yet on the very
    /// first layout pass, in which case a later resize/collection-changed
    /// call finds it instead).
    /// </summary>
    private Canvas? FindWidgetsCanvas() => _widgetsCanvas ??= FindVisualChild<Canvas>(WidgetsHost);

    private static T? FindVisualChild<T>(DependencyObject parent) where T : DependencyObject
    {
        var childCount = VisualTreeHelper.GetChildrenCount(parent);
        for (var i = 0; i < childCount; i++)
        {
            var child = VisualTreeHelper.GetChild(parent, i);
            if (child is T typed)
            {
                return typed;
            }

            var descendant = FindVisualChild<T>(child);
            if (descendant is not null)
            {
                return descendant;
            }
        }

        return null;
    }

    /// <summary>Scrolls a widget just added from the picker into sight - once it has been laid out, which is why this waits for the Loaded priority.</summary>
    private void OnWidgetAdded(object? sender, DashboardWidgetViewModel widget)
    {
        Dispatcher.InvokeAsync(
            () =>
            {
                if (WidgetsHost.ItemContainerGenerator.ContainerFromItem(widget) is FrameworkElement container)
                {
                    container.BringIntoView();
                }
            },
            System.Windows.Threading.DispatcherPriority.Loaded);
    }

    private void OnHeaderDragStarted(object sender, DragStartedEventArgs e)
    {
        if (((FrameworkElement)sender).DataContext is not DashboardWidgetViewModel widget)
        {
            return;
        }

        _draggingWidget = widget;
        _dragStartMousePosition = Mouse.GetPosition(this);
        _dragOriginColumn = widget.Column;
        _dragOriginRow = widget.Row;
    }

    /// <summary>
    /// Recomputes the target cell from the mouse's absolute position relative
    /// to this control (which never moves as a result of anything below) each
    /// event, rather than accumulating <see cref="DragDeltaEventArgs"/>'s own
    /// Horizontal/VerticalChange. Thumb computes those relative to itself, so
    /// once a whole-cell jump moves the widget - and the Thumb inside it -
    /// out from under the cursor, the next such delta is corrupted by that
    /// self-inflicted shift, which produces another jump to compensate, then
    /// another to compensate for that one: a runaway oscillation the user
    /// sees as violent shaking. Measuring fresh against a fixed reference
    /// point every time sidesteps the feedback loop entirely.
    /// </summary>
    private void OnHeaderDragDelta(object sender, DragDeltaEventArgs e)
    {
        if (_draggingWidget is null)
        {
            return;
        }

        var current = Mouse.GetPosition(this);
        var targetColumn = Math.Clamp(_dragOriginColumn + (int)Math.Round((current.X - _dragStartMousePosition.X) / DashboardWidget.CellSize), 0, MaxGridExtent);
        var targetRow = Math.Clamp(_dragOriginRow + (int)Math.Round((current.Y - _dragStartMousePosition.Y) / DashboardWidget.CellSize), 0, MaxGridExtent);

        if (targetColumn == _draggingWidget.Column && targetRow == _draggingWidget.Row)
        {
            return;
        }

        _draggingWidget.Column = targetColumn;
        _draggingWidget.Row = targetRow;

        ViewModel?.Reflow(_draggingWidget);
        ShowGuides(_draggingWidget);
        UpdateCanvasExtent();
    }

    private void OnHeaderDragCompleted(object sender, DragCompletedEventArgs e)
    {
        _draggingWidget = null;
        GuideLayer.Children.Clear();

        if (DataContext is DashboardViewModel viewModel)
        {
            viewModel.CommitLayout();
        }
    }

    private void OnResizeDragStarted(object sender, DragStartedEventArgs e)
    {
        if (((FrameworkElement)sender).DataContext is not DashboardWidgetViewModel widget)
        {
            return;
        }

        _resizingWidget = widget;
        _resizeStartMousePosition = Mouse.GetPosition(this);
        _resizeOriginColumnSpan = widget.ColumnSpan;
        _resizeOriginRowSpan = widget.RowSpan;
    }

    /// <summary>Same fixed-reference-point approach as dragging - see its remarks - applied to the widget's span instead of its position.</summary>
    private void OnResizeDragDelta(object sender, DragDeltaEventArgs e)
    {
        if (_resizingWidget is null)
        {
            return;
        }

        var current = Mouse.GetPosition(this);
        var targetColumnSpan = Math.Clamp(_resizeOriginColumnSpan + (int)Math.Round((current.X - _resizeStartMousePosition.X) / DashboardWidget.CellSize), DashboardWidget.MinColumnSpan, MaxGridExtent);
        var targetRowSpan = Math.Clamp(_resizeOriginRowSpan + (int)Math.Round((current.Y - _resizeStartMousePosition.Y) / DashboardWidget.CellSize), DashboardWidget.MinRowSpan, MaxGridExtent);

        if (targetColumnSpan == _resizingWidget.ColumnSpan && targetRowSpan == _resizingWidget.RowSpan)
        {
            return;
        }

        _resizingWidget.ColumnSpan = targetColumnSpan;
        _resizingWidget.RowSpan = targetRowSpan;

        ViewModel?.Reflow(_resizingWidget);
        ShowGuides(_resizingWidget);
        UpdateCanvasExtent();
    }

    private void OnResizeDragCompleted(object sender, DragCompletedEventArgs e)
    {
        _resizingWidget = null;
        GuideLayer.Children.Clear();

        if (DataContext is DashboardViewModel viewModel)
        {
            viewModel.CommitLayout();
        }
    }

    /// <summary>A generous ceiling on column/row/span, just to stop a wild mouse movement from growing the canvas without bound.</summary>
    private const int MaxGridExtent = 500;

    private DashboardViewModel? ViewModel => DataContext as DashboardViewModel;

    /// <summary>
    /// Alignment guides (#278): dashed lines where the widget being dragged
    /// or resized lines up with another's edges - see DashboardGrid.AlignedEdges.
    /// </summary>
    private void ShowGuides(DashboardWidgetViewModel moving)
    {
        GuideLayer.Children.Clear();
        if (ViewModel is not { } viewModel || FindWidgetsCanvas() is not { } canvas)
        {
            return;
        }

        static GridItem Item(DashboardWidgetViewModel w) => new(w.Id, w.Column, w.Row, w.ColumnSpan, w.RowSpan);
        var (columns, rows) = DashboardGrid.AlignedEdges(Item(moving), viewModel.Widgets.Select(Item));
        var accent = (Brush)FindResource("AccentBrush");

        Line Guide(double x1, double y1, double x2, double y2) => new()
        {
            X1 = x1, Y1 = y1, X2 = x2, Y2 = y2,
            Stroke = accent,
            StrokeThickness = 1,
            StrokeDashArray = new DoubleCollection { 4, 3 },
            SnapsToDevicePixels = true,
        };

        foreach (var column in columns)
        {
            var x = column * DashboardWidget.CellSize;
            GuideLayer.Children.Add(Guide(x, 0, x, canvas.ActualHeight));
        }

        foreach (var row in rows)
        {
            var y = row * DashboardWidget.CellSize;
            GuideLayer.Children.Add(Guide(0, y, canvas.ActualWidth, y));
        }
    }

    /// <summary>In edit mode, clicking a widget selects it - the keys act on it (#278).</summary>
    private void OnWidgetMouseDown(object sender, MouseButtonEventArgs e)
    {
        if (ViewModel is { IsEditMode: true } viewModel && ((FrameworkElement)sender).DataContext is DashboardWidgetViewModel widget)
        {
            viewModel.SelectedWidget = widget;
            Focus();
        }
    }

    /// <summary>The ⋯ opens its menu on a plain click, as a menu button does (#274).</summary>
    private void OnMoreClick(object sender, RoutedEventArgs e)
    {
        if (sender is Button { ContextMenu: { } menu } button)
        {
            menu.DataContext = button.DataContext;
            menu.PlacementTarget = button;
            menu.Placement = PlacementMode.Bottom;
            menu.IsOpen = true;
        }
    }

    private void OnRenameBoxVisibleChanged(object sender, DependencyPropertyChangedEventArgs e)
    {
        if (sender is TextBox { IsVisible: true } box)
        {
            Dispatcher.InvokeAsync(() =>
            {
                box.Focus();
                box.SelectAll();
            }, System.Windows.Threading.DispatcherPriority.Input);
        }
    }

    /// <summary>Enter keeps the new title, Esc the old one; either way renaming ends.</summary>
    private void OnRenameBoxKeyDown(object sender, KeyEventArgs e)
    {
        if (sender is not TextBox { DataContext: DashboardWidgetViewModel widget } box || e.Key is not (Key.Enter or Key.Escape))
        {
            return;
        }

        var binding = box.GetBindingExpression(TextBox.TextProperty);
        if (e.Key == Key.Enter)
        {
            binding?.UpdateSource();
        }
        else
        {
            binding?.UpdateTarget();
        }

        widget.IsRenaming = false;
        e.Handled = true;
    }

    private void OnRenameBoxLostFocus(object sender, KeyboardFocusChangedEventArgs e)
    {
        if (sender is TextBox { DataContext: DashboardWidgetViewModel widget })
        {
            widget.IsRenaming = false;
        }
    }

    /// <summary>
    /// The keys in edit mode (#278): arrows move the selected widget a cell,
    /// Shift + arrows resize it, Del removes it, F2 renames it, Ctrl+D
    /// duplicates it, Ctrl+Z undoes and Esc lets go of it. Typing in a box
    /// (renaming, the set-up panel) is left alone.
    /// </summary>
    private void OnPreviewKeyDown(object sender, KeyEventArgs e)
    {
        if (ViewModel is not { IsEditMode: true } viewModel || e.OriginalSource is TextBoxBase)
        {
            return;
        }

        var ctrl = Keyboard.Modifiers.HasFlag(ModifierKeys.Control);
        var shift = Keyboard.Modifiers.HasFlag(ModifierKeys.Shift);

        if (ctrl && e.Key == Key.Z)
        {
            viewModel.UndoCommand.Execute(null);
            e.Handled = true;
            return;
        }

        if (viewModel.SelectedWidget is not { } widget)
        {
            return;
        }

        switch (e.Key)
        {
            case Key.Left:
                viewModel.Nudge(-1, 0, shift);
                break;
            case Key.Right:
                viewModel.Nudge(1, 0, shift);
                break;
            case Key.Up:
                viewModel.Nudge(0, -1, shift);
                break;
            case Key.Down:
                viewModel.Nudge(0, 1, shift);
                break;
            case Key.Delete:
                widget.RemoveCommand.Execute(null);
                break;
            case Key.F2:
                widget.RenameCommand.Execute(null);
                break;
            case Key.D when ctrl:
                widget.DuplicateCommand.Execute(null);
                break;
            case Key.Escape:
                viewModel.SelectedWidget = null;
                break;
            default:
                return;
        }

        UpdateCanvasExtent();
        e.Handled = true;
    }

    /// <summary>
    /// Shift-clicking a severity chip on an Alerts widget isolates that
    /// severity instead of toggling it normally - handled here (rather than a
    /// Command) so the plain click still flips <c>IsChecked</c> via its
    /// binding unchanged. The chip's own DataContext (not this view's) is the
    /// widget, since this fires from inside the widget's DataTemplate.
    /// </summary>
    private void AlertSeverityBadge_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (Keyboard.Modifiers != ModifierKeys.Shift)
        {
            return;
        }

        // The toggles live in the title bar (#212), with the header as their DataContext.
        if (((FrameworkElement)sender).DataContext is not AlertsWidgetHeader { Widget: var widget })
        {
            return;
        }

        var severity = ((ToggleButton)sender).Tag as string == "Critical"
            ? AlertSeverity.Critical
            : AlertSeverity.Warning;

        widget.IsolateSeverity(severity);
        e.Handled = true;
    }
}
