using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using DesktopNMS.Core.Configuration;
using DesktopNMS.ViewModels;

namespace DesktopNMS.Views;

/// <summary>
/// The Dashboard tab: at-a-glance widgets laid out on a snapped grid. Widgets
/// are positioned in whole grid cells (<see cref="DashboardWidget.CellSize"/>
/// pixels each); dragging or resizing one over another displaces it straight
/// down (cascading to whatever that newly overlaps) rather than just being
/// blocked, so rearranging feels like reflowing a layout instead of picking a
/// careful gap to squeeze into.
/// </summary>
public partial class DashboardView : UserControl
{
    private Canvas? _widgetsCanvas;

    private DashboardWidgetViewModel? _draggingWidget;
    private Point _dragStartMousePosition;
    private int _dragOriginColumn;
    private int _dragOriginRow;

    private DashboardWidgetViewModel? _resizingWidget;
    private Point _resizeStartMousePosition;
    private int _resizeOriginColumnSpan;
    private int _resizeOriginRowSpan;

    public DashboardView()
    {
        InitializeComponent();
    }

    private void OnLoaded(object sender, RoutedEventArgs e)
    {
        if (DataContext is DashboardViewModel viewModel)
        {
            viewModel.Widgets.CollectionChanged -= OnWidgetsCollectionChanged;
            viewModel.Widgets.CollectionChanged += OnWidgetsCollectionChanged;
        }

        UpdateCanvasExtent();
    }

    private void OnWidgetsCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e) => UpdateCanvasExtent();

    private void OnCanvasSizeChanged(object sender, SizeChangedEventArgs e) => UpdateCanvasExtent();

    /// <summary>
    /// Grows the canvas to whatever is bigger - the visible viewport, or the
    /// furthest extent of any widget - so dragging/growing a widget past the
    /// current view makes the canvas scrollable rather than clipping it, and
    /// shrinks back down (no further than the viewport) once nothing needs
    /// the extra room any more.
    /// </summary>
    private void UpdateCanvasExtent()
    {
        if (DataContext is not DashboardViewModel viewModel)
        {
            return;
        }

        var canvas = FindWidgetsCanvas();
        if (canvas is null)
        {
            return;
        }

        double contentWidth = 0;
        double contentHeight = 0;

        foreach (var widget in viewModel.Widgets)
        {
            contentWidth = Math.Max(contentWidth, (widget.Column + widget.ColumnSpan) * DashboardWidget.CellSize);
            contentHeight = Math.Max(contentHeight, (widget.Row + widget.RowSpan) * DashboardWidget.CellSize);
        }

        canvas.Width = Math.Max(CanvasScroll.ActualWidth, contentWidth);
        canvas.Height = Math.Max(CanvasScroll.ActualHeight, contentHeight);
    }

    /// <summary>
    /// The Canvas is generated by <c>WidgetsHost</c>'s <see cref="ItemsControl.ItemsPanel"/>
    /// template, so it has no code-behind field of its own - it must be found
    /// in the visual tree instead, once it exists (it may not yet on the very
    /// first layout pass, in which case a later resize/collection-changed
    /// call finds it instead).
    /// </summary>
    private Canvas? FindWidgetsCanvas() => _widgetsCanvas ??= FindVisualChild<Canvas>(WidgetsHost);

    private static T? FindVisualChild<T>(DependencyObject parent) where T : DependencyObject
    {
        var childCount = VisualTreeHelper.GetChildrenCount(parent);
        for (var i = 0; i < childCount; i++)
        {
            var child = VisualTreeHelper.GetChild(parent, i);
            if (child is T typed)
            {
                return typed;
            }

            var descendant = FindVisualChild<T>(child);
            if (descendant is not null)
            {
                return descendant;
            }
        }

        return null;
    }

    /// <summary>"Add widget" opens its picker menu on a left click, not just the usual right click.</summary>
    private void OnAddWidgetClick(object sender, RoutedEventArgs e)
    {
        var button = (Button)sender;
        if (button.ContextMenu is { } menu)
        {
            menu.PlacementTarget = button;
            menu.IsOpen = true;
        }
    }

    private void OnHeaderDragStarted(object sender, DragStartedEventArgs e)
    {
        if (((FrameworkElement)sender).DataContext is not DashboardWidgetViewModel widget)
        {
            return;
        }

        _draggingWidget = widget;
        _dragStartMousePosition = Mouse.GetPosition(this);
        _dragOriginColumn = widget.Column;
        _dragOriginRow = widget.Row;
    }

    /// <summary>
    /// Recomputes the target cell from the mouse's absolute position relative
    /// to this control (which never moves as a result of anything below) each
    /// event, rather than accumulating <see cref="DragDeltaEventArgs"/>'s own
    /// Horizontal/VerticalChange. Thumb computes those relative to itself, so
    /// once a whole-cell jump moves the widget - and the Thumb inside it -
    /// out from under the cursor, the next such delta is corrupted by that
    /// self-inflicted shift, which produces another jump to compensate, then
    /// another to compensate for that one: a runaway oscillation the user
    /// sees as violent shaking. Measuring fresh against a fixed reference
    /// point every time sidesteps the feedback loop entirely.
    /// </summary>
    private void OnHeaderDragDelta(object sender, DragDeltaEventArgs e)
    {
        if (_draggingWidget is null)
        {
            return;
        }

        var current = Mouse.GetPosition(this);
        var targetColumn = Math.Clamp(_dragOriginColumn + (int)Math.Round((current.X - _dragStartMousePosition.X) / DashboardWidget.CellSize), 0, MaxGridExtent);
        var targetRow = Math.Clamp(_dragOriginRow + (int)Math.Round((current.Y - _dragStartMousePosition.Y) / DashboardWidget.CellSize), 0, MaxGridExtent);

        if (targetColumn == _draggingWidget.Column && targetRow == _draggingWidget.Row)
        {
            return;
        }

        _draggingWidget.Column = targetColumn;
        _draggingWidget.Row = targetRow;

        ReflowFrom(_draggingWidget);
        UpdateCanvasExtent();
    }

    private void OnHeaderDragCompleted(object sender, DragCompletedEventArgs e)
    {
        _draggingWidget = null;

        if (DataContext is DashboardViewModel viewModel)
        {
            viewModel.CommitLayout();
        }
    }

    private void OnResizeDragStarted(object sender, DragStartedEventArgs e)
    {
        if (((FrameworkElement)sender).DataContext is not DashboardWidgetViewModel widget)
        {
            return;
        }

        _resizingWidget = widget;
        _resizeStartMousePosition = Mouse.GetPosition(this);
        _resizeOriginColumnSpan = widget.ColumnSpan;
        _resizeOriginRowSpan = widget.RowSpan;
    }

    /// <summary>Same fixed-reference-point approach as dragging - see its remarks - applied to the widget's span instead of its position.</summary>
    private void OnResizeDragDelta(object sender, DragDeltaEventArgs e)
    {
        if (_resizingWidget is null)
        {
            return;
        }

        var current = Mouse.GetPosition(this);
        var targetColumnSpan = Math.Clamp(_resizeOriginColumnSpan + (int)Math.Round((current.X - _resizeStartMousePosition.X) / DashboardWidget.CellSize), DashboardWidget.MinColumnSpan, MaxGridExtent);
        var targetRowSpan = Math.Clamp(_resizeOriginRowSpan + (int)Math.Round((current.Y - _resizeStartMousePosition.Y) / DashboardWidget.CellSize), DashboardWidget.MinRowSpan, MaxGridExtent);

        if (targetColumnSpan == _resizingWidget.ColumnSpan && targetRowSpan == _resizingWidget.RowSpan)
        {
            return;
        }

        _resizingWidget.ColumnSpan = targetColumnSpan;
        _resizingWidget.RowSpan = targetRowSpan;

        ReflowFrom(_resizingWidget);
        UpdateCanvasExtent();
    }

    private void OnResizeDragCompleted(object sender, DragCompletedEventArgs e)
    {
        _resizingWidget = null;

        if (DataContext is DashboardViewModel viewModel)
        {
            viewModel.CommitLayout();
        }
    }

    /// <summary>A generous ceiling on column/row/span, just to stop a wild mouse movement from growing the canvas without bound.</summary>
    private const int MaxGridExtent = 500;

    /// <summary>Safety cap on the reflow cascade below - see its remarks.</summary>
    private const int MaxReflowIterations = 2000;

    /// <summary>
    /// Pushes anything <paramref name="anchor"/> now overlaps straight down to
    /// clear it, then re-checks whatever was just pushed against everyone else
    /// (its new position may overlap something new), cascading outward.
    /// Terminates because a widget is only ever pushed to a strictly larger
    /// row than it already had, so the total displacement is bounded; the
    /// iteration cap is a backstop, not something normal use should ever hit.
    /// </summary>
    private void ReflowFrom(DashboardWidgetViewModel anchor)
    {
        if (DataContext is not DashboardViewModel viewModel)
        {
            return;
        }

        var all = viewModel.Widgets;
        var queue = new Queue<DashboardWidgetViewModel>();
        queue.Enqueue(anchor);

        var iterations = 0;

        while (queue.Count > 0 && iterations++ < MaxReflowIterations)
        {
            var current = queue.Dequeue();

            foreach (var other in all)
            {
                if (ReferenceEquals(other, current) || ReferenceEquals(other, anchor))
                {
                    continue;
                }

                if (!Overlaps(current, other))
                {
                    continue;
                }

                var newRow = current.Row + current.RowSpan;
                if (other.Row < newRow)
                {
                    other.Row = newRow;
                    queue.Enqueue(other);
                }
            }
        }
    }

    private static bool Overlaps(DashboardWidgetViewModel a, DashboardWidgetViewModel b)
        => a.Column < b.Column + b.ColumnSpan
        && a.Column + a.ColumnSpan > b.Column
        && a.Row < b.Row + b.RowSpan
        && a.Row + a.RowSpan > b.Row;
}
