// <auto-generated>
//   By tools/Generate-GraphSeriesNames.cs from LibreNMS 08241cf197188049e2fdf161d5b0298cce870caa.
//   Don't edit by hand - run it again instead.
// </auto-generated>

namespace DesktopNMS.Core.Graphs;

public static partial class GraphSeriesNames
{
    /// <summary>The LibreNMS commit the names were read from.</summary>
    public const string LibreNmsCommit = "08241cf197188049e2fdf161d5b0298cce870caa";

    private static readonly Dictionary<string, Definition> Generated = new(StringComparer.Ordinal)
    {
        ["device_bigip_ltm_vs_bytes"] = new([new("Bits In", "#330033"), new("Bits Out", "#FF6600")], LegendInOrder: true),
        ["device_bigip_ltm_vs_pkts"] = new([new("Packets in", "#330033"), new("Packets out", "#FF6600")], LegendInOrder: true),
        ["device_bigip_system_tps"] = new([new("Native", "#002A97"), new("Compat", "#4444FF"), new("Difference", "#C0C0C0")], LegendInOrder: true),
        ["device_cambium-epmp-frameUtilization"] = new([new("Downlink Frame Utilization", "#FF0000"), new("Uplink Frame Utilization", "#003EFF")], LegendInOrder: true),
        ["device_cambium_250_dataRate"] = new([new("Receive Data Rate", "#0000FF"), new("Transmit Data Rate", "#FF0000"), new("Aggregate Data Rate", "#008080")], LegendInOrder: true),
        ["device_cambium_250_modulationMode"] = new([new("Receive Modulation", "#0000FF"), new("Transmit Modulation", "#FF0000")], LegendInOrder: true),
        ["device_cambium_250_receivePower"] = new([new("Receive Power", "#00FF00"), new("Noise Floor", "#000000")], LegendInOrder: true),
        ["device_cambium_650_dataRate"] = new([new("Receive Data Rate", "#0000FF"), new("Transmit Data Rate", "#FF0000"), new("Aggregate Data Rate", "#FFF000")], LegendInOrder: true),
        ["device_cambium_650_modulationMode"] = new([new("Receive Modulation", "#0000FF"), new("Transmit Modulation", "#FF0000")], LegendInOrder: true),
        ["device_cambium_epmp_RFStatus"] = new([new("RSSI", "#FF0000"), new("SNR", "#0000FF")], LegendInOrder: true),
        ["device_cambium_epmp_access"] = new([new("Entry Attempts", "#FFF000"), new("Entry Access", "#00FF00"), new("Auth Failure", "#FF0000")], LegendInOrder: true),
        ["device_cambium_epmp_gps"] = new([new("GPS Number Tracked", "#00B200"), new("GPS Number Visible", "#FFFF00")], LegendInOrder: true),
        ["device_cambium_epmp_modulation"] = new([new("Uplink", "#8F5E99"), new("Downlink", "#0000FF")], LegendInOrder: true),
        ["device_cambium_epmp_traffic"] = new([new("RX Traffic", "#00AA00"), new("TX Traffic", "#0000AA")], LegendInOrder: true),
        ["device_canopy-generic-frameUtilization"] = new([new("Downlink Frame Utilization", "#FF0000"), new("Uplink Frame Utilization", "#003EFF")], LegendInOrder: true),
        ["device_canopy_generic_450_linkRadioDbm"] = new([new("Vertical", "#FF0000"), new("Horizontal", "#003EFF")], LegendInOrder: true),
        ["device_canopy_generic_450_ptpSNR"] = new([new("Vertical", "#FF0000"), new("Horizontal", "#00B2EE")], LegendInOrder: true),
        ["device_canopy_generic_450_slaveHV"] = new([new("Vertical", "#FF0000"), new("Horizontal", "#003EFF")], LegendInOrder: true),
        ["device_canopy_generic_450_slaveSNR"] = new([new("Vertical", "#FF0000"), new("Horizontal", "#00B2EE")], LegendInOrder: true),
        ["device_canopy_generic_errorCount"] = new([new("In Error Count", "#FF0000"), new("Out Error Count", "#00FF00")], LegendInOrder: true),
        ["device_canopy_generic_gpsStats"] = new([new("Visible", "#0099FF"), new("Tracked", "#00FF00")], LegendInOrder: true),
        ["device_canopy_generic_radioDbm"] = new([new("Radio Dbm", "#00E5EE"), new("Min", "#00CD66"), new("Max", "#B272A6"), new("Avg", "#CC7F32")], LegendInOrder: true),
        ["device_canopy_generic_regCount"] = new([new("Registered Sm", "#FF0000"), new("Amount Failed", "#000000")], LegendInOrder: true),
        ["device_canopy_generic_signalHV"] = new([new("Vertical", "#FF0000"), new("Horizontal", "#003EFF"), new("Combined", "#FFA500")], LegendInOrder: true),
        ["device_canopy_generic_snrHV"] = new([new("Vertical", "#FF0000"), new("Horizontal", "#003EFF")], LegendInOrder: true),
        ["device_cipsec_flow_pkts"] = new([new("In", "#330033"), new("Out", "#FF6600")], LegendInOrder: true),
        ["device_cipsec_flow_stats"] = new([new("InAuths", "#CC0000"), new("OutAuths", "#008C00"), new("InDecrypts", "#4096EE"), new("OutEncrypts", "#73880A"), new("InDrops", "#D01F3C"), new("InReplayDrops", "#36393D"), new("OutDrops", "#FF0084"), new("InAuthFail", "#91B13C"), new("OutAuthFail", "#CC0000"), new("InDecryptFails", "#008C00"), new("OutEncryptFails", "#4096EE"), new("ProtocolUseFails", "#73880A"), new("NoSaFails", "#D01F3C"), new("SysCapFails", "#36393D")], LegendInOrder: true),
        ["device_cras_sessions"] = new([new("SSL VPN Client", "#1985A1"), new("Clientless VPN", "#4C5C68"), new("IPSEC", "#46494C"), new("LAN-to-LAN", "#C5C3C6"), new("Email", "#DCDCDD"), new("Load Balancer", "#FFFFFF"), new("Total", "#000000")], LegendInOrder: true),
        ["device_ipSystemStats"] = new([new("InReceives   v4", "#CDEB8B"), new("OutRequests  v4", "#C3D9FF"), new("InForward    v4", "#AF63AF"), new("OutForward   v4", "#AF63AF"), new("InDelivers   v4", "#00CC00"), new("v6", "#3F003F")], LegendInOrder: true),
        ["device_ipsystemstats_ipv4"] = new([new("InReceives   v4", "#7D9B5B"), new("InForward    v4", "#AF63AF"), new("OutRequests  v4", "#C3D9FF"), new("OutForward   v4", "#AF63AF")], LegendInOrder: true),
        ["device_ipsystemstats_ipv6"] = new([new("InReceives   v6", "#7D9B5B"), new("InForward    v6", "#AF63AF"), new("OutRequests  v6", "#C3D9FF"), new("OutForward   v6", "#AF63AF")], LegendInOrder: true),
        ["device_netscaler_tcp_conn"] = new([new("Client", "#008800"), new("Server", "#880000")], LegendInOrder: true),
        ["device_netscaler_tcp_pkts"] = new([new("In", "#330033"), new("Out", "#FF6600")], LegendInOrder: true),
        ["device_netstat_snmp"] = new([new("InTraps", "#CC0000"), new("InTotalReqVars", "#008C00"), new("InTotalSetVars", "#4096EE"), new("OutTraps", "#73880A"), new("OutGetResponses", "#D01F3C"), new("OutSetRequests", "#36393D")], LegendInOrder: false),
        ["device_netstat_snmp_pkt"] = new([new("In", "#330033"), new("Out", "#FF6600")], LegendInOrder: true),
        ["device_netstat_tcp"] = new([new("InSegs", "#CC0000"), new("OutSegs", "#008C00"), new("ActiveOpens", "#4096EE"), new("PassiveOpens", "#73880A"), new("AttemptFails", "#D01F3C"), new("EstabResets", "#36393D"), new("RetransSegs", "#FF0084")], LegendInOrder: true),
        ["device_netstat_udp"] = new([new("InDatagrams", "#CC0000"), new("OutDatagrams", "#008C00"), new("InErrors", "#4096EE"), new("NoPorts", "#73880A")], LegendInOrder: true),
        ["device_ping_perf"] = new([new("Milliseconds", "#663399"), new("25th percentile", "#22CCBB"), new("50th percentile", "#00BBCC"), new("75th percentile", "#0099CC"), new("1 hour average", "#3366BB"), new("1 day average", "#AA3355"), new("1 week average", "#881177")], LegendInOrder: false),
        ["device_poller_perf"] = new([new("Seconds", "#663399"), new("25th percentile", "#22CCBB"), new("50th percentile", "#00BBCC"), new("75th percentile", "#0099CC"), new("1 hour average", "#3366BB"), new("1 day average", "#AA3355"), new("1 week average", "#881177")], LegendInOrder: false),
        ["device_purestorage_bandwidth"] = new([new("Read Bandwidth", "#00AA00"), new("Write Bandwidth", "#0000AA")], LegendInOrder: true),
        ["device_purestorage_iops"] = new([new("Read IOPS", "#00AA00"), new("Write IOPS", "#0000AA")], LegendInOrder: true),
        ["device_purestorage_latency"] = new([new("Read Latency", "#00AA00"), new("Write Latency", "#0000AA")], LegendInOrder: true),
        ["device_qos_routeros_simple_drop"] = new([new("In", "#880000"), new("Out", "#B68A00")], LegendInOrder: true),
        ["device_screenos_sessions"] = new([new("Maxiumum", "#CC0000"), new("Allocated", "#008C00"), new("Failed", "#4096EE")], LegendInOrder: true),
        ["device_siklu_rfinterfaceOctets"] = new([new("In", "#00FF00"), new("Out", "#CC0000")], LegendInOrder: true),
        ["device_siklu_rfinterfaceOtherOctets"] = new([new("Good Octets", "#00FF00"), new("Errored Octets", "#CC0000"), new("In Idle Octets", "#0022FF"), new("Out Idle Octets", "#DD9CFB")], LegendInOrder: true),
        ["device_siklu_rfinterfaceOtherPkts"] = new([new("Good Pkts", "#00FF00"), new("Errored Pkts", "#CC0000"), new("Lost Pkts", "#0022FF")], LegendInOrder: true),
        ["device_siklu_rfinterfacePkts"] = new([new("In", "#00FF00"), new("Out", "#CC0000")], LegendInOrder: true),
        ["device_sla_icmpjitter_jitter"] = new([new("Src to Dst (ms)", "#0000EE"), new("Dst to Src (ms)", "#008C00")], LegendInOrder: true),
        ["device_sla_icmpjitter_latency"] = new([new("Src to Dst (ms)", "#0000EE"), new("Dst to Src (ms)", "#008C00")], LegendInOrder: true),
        ["device_sla_icmpjitter_lost"] = new([new("Packets Lost", "#008C00"), new("Late Arrival", "#CC0000")], LegendInOrder: true),
        ["device_sla_icmpjitter_oos"] = new([new("Src to Dst (ms)", "#0000EE"), new("Dst to Src (ms)", "#008C00")], LegendInOrder: true),
        ["device_sla_jitter"] = new([new("Src to Dst (ms)", "#0000EE"), new("Dst to Src (ms)", "#008C00")], LegendInOrder: true),
        ["device_sla_jitter-loss"] = new([new("Src to Dst (pkts)", "#FF3300"), new("Dst to Src (pkts)", "#FF6633")], LegendInOrder: true),
        ["device_sla_jitter-loss-percent"] = new([new("Src to Dst (%)", "#0000EE"), new("Dst to Src (%)", "#008C00")], LegendInOrder: true),
        ["device_sla_jitter-lost"] = new([new("Out of Sequence", "#0000EE"), new("Missing in Action", "#008C00"), new("Late Arrival", "#CC0000")], LegendInOrder: true),
        ["device_ubnt_airfiber_Capacity"] = new([new("Rx Rate", "#00FF00"), new("Tx Rate", "#CC0000")], LegendInOrder: true),
        ["device_ubnt_airfiber_RadioFreqs"] = new([new("Rx Frequency", "#00FF00"), new("Tx Frequency", "#CC0000")], LegendInOrder: true),
        ["device_ubnt_airfiber_RadioTemp"] = new([new("Radio 0", "#00FF00"), new("Radio 1", "#CC0000")], LegendInOrder: true),
        ["device_ubnt_airfiber_RxPower"] = new([new("Rx Chain0 Power", "#00FF00"), new("Rx Chain1 Power", "#CC0000")], LegendInOrder: true),
        ["device_ucd_cpu"] = new([new("user", "#C02020"), new("nice", "#008F00"), new("system", "#EA8F00"), new("idle", "#000077")], LegendInOrder: true),
        ["device_ucd_load"] = new([new("1 Min", "#FFEEAA"), new("5 Min", "#EA8F00"), new("15 Min", "#CC0000")], LegendInOrder: true),
        ["device_uptime"] = new([new("Uptime", "#CAE853"), new("25th percentile", "#B2D849"), new("50th percentile", "#94C63D"), new("75th percentile", "#75BA30"), new("1 hour average", "#49A81E"), new("1 day average", "#0C990C"), new("1 week average", "#CAE853")], LegendInOrder: false),
    };
}
