// Generates src/DesktopNMS.Core/Graphs/GraphSeriesNames.Generated.cs: for each of
// LibreNMS's device graphs whose series can be read from its source, the name
// and colour of each named series - so the app can draw its own legend for
// them (see GraphSeriesNames). Run from the repository root:
//
//   GH_TOKEN=$(gh auth token) dotnet run tools/Generate-GraphSeriesNames.cs [librenms-commit]
//
// It reads LibreNMS's own files at that commit (master by default) from
// GitHub: includes/html/graphs/device/*.inc.php and the graph_colours
// palettes in resources/definitions/config_definitions.json. Graphs whose
// series come from the database, or are built in ways this doesn't follow,
// are left out - the app keeps LibreNMS's legend for those.

using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

var sha = args.Length > 0 ? args[0] : "master";
using var http = new HttpClient();
http.DefaultRequestHeaders.UserAgent.ParseAdd("DashyNMS-generator");

// GitHub's API turns away unauthenticated callers quickly - pass a token in GH_TOKEN (e.g. GH_TOKEN=$(gh auth token)).
if (Environment.GetEnvironmentVariable("GH_TOKEN") is { Length: > 0 } token)
{
    http.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
}

if (sha == "master")
{
    var commit = JsonDocument.Parse(await http.GetStringAsync("https://api.github.com/repos/librenms/librenms/commits/master")).RootElement;
    sha = commit.GetProperty("sha").GetString()!;
}

string Raw(string path) => http.GetStringAsync($"https://raw.githubusercontent.com/librenms/librenms/{sha}/{path}").GetAwaiter().GetResult();

var config = JsonDocument.Parse(Raw("resources/definitions/config_definitions.json"));
var palettes = new Dictionary<string, string[]>();
// Each palette is its own setting: "graph_colours.mixed": { "default": ["CC0000", ...] }.
if (config.RootElement.TryGetProperty("config", out var cfg))
{
    foreach (var setting in cfg.EnumerateObject().Where(s => s.Name.StartsWith("graph_colours.", StringComparison.Ordinal)))
    {
        if (setting.Value.TryGetProperty("default", out var colours) && colours.ValueKind == JsonValueKind.Array)
        {
            palettes[setting.Name["graph_colours.".Length..]] = colours.EnumerateArray().Select(c => c.GetString()!).ToArray();
        }
    }
}

var files = JsonDocument.Parse(await http.GetStringAsync($"https://api.github.com/repos/librenms/librenms/contents/includes/html/graphs/device?ref={sha}")).RootElement;
var names = files.EnumerateArray().Select(f => f.GetProperty("name").GetString()!).Where(n => n.EndsWith(".inc.php", StringComparison.Ordinal)).ToList();

var entries = new SortedDictionary<string, List<(string Name, string? Colour)>>(StringComparer.Ordinal);
var orderedOnly = new HashSet<string>();
foreach (var file in names)
{
    var graph = "device_" + file[..^".inc.php".Length];
    var php = Raw("includes/html/graphs/device/" + file);
    var series = Read(php, out var legendInOrder);
    if (series is { Count: > 1 })
    {
        entries[graph] = series;
        if (legendInOrder)
        {
            orderedOnly.Add(graph);
        }
    }
}

var output = new StringBuilder();
output.AppendLine("// <auto-generated>");
output.AppendLine($"//   By tools/Generate-GraphSeriesNames.cs from LibreNMS {sha}.");
output.AppendLine("//   Don't edit by hand - run it again instead.");
output.AppendLine("// </auto-generated>");
output.AppendLine();
output.AppendLine("namespace DesktopNMS.Core.Graphs;");
output.AppendLine();
output.AppendLine("public static partial class GraphSeriesNames");
output.AppendLine("{");
output.AppendLine($"    /// <summary>The LibreNMS commit the names were read from.</summary>");
output.AppendLine($"    public const string LibreNmsCommit = \"{sha}\";");
output.AppendLine();
output.AppendLine("    private static readonly Dictionary<string, Definition> Generated = new(StringComparer.Ordinal)");
output.AppendLine("    {");
foreach (var (graph, series) in entries)
{
    var items = string.Join(", ", series.Select(s => $"new(\"{Escape(s.Name)}\", {(s.Colour is null ? "null" : $"\"#{s.Colour.ToUpperInvariant()}\"")})"));
    output.AppendLine($"        [\"{graph}\"] = new([{items}], LegendInOrder: {(orderedOnly.Contains(graph) ? "true" : "false")}),");
}

output.AppendLine("    };");
output.AppendLine("}");

var target = Path.Combine("src", "DesktopNMS.Core", "Graphs", "GraphSeriesNames.Generated.cs");
File.WriteAllText(target, output.ToString().Replace("\r\n", "\n", StringComparison.Ordinal));
Console.WriteLine($"{entries.Count} of {names.Count} device graphs named, from LibreNMS {sha} -> {target}");
return;

// ------------------------------------------------------------------ reading

List<(string Name, string? Colour)>? Read(string php, out bool legendInOrder)
{
    legendInOrder = true;
    var template = Regex.Match(php, @"graphs/(generic_[a-z0-9_]+)\.inc\.php").Groups[1].Value;
    var colours = Regex.Match(php, @"\$colours\s*=\s*'([a-z0-9_]+)'").Groups[1].Value;

    switch (template)
    {
        case "generic_multi_line" or "generic_multi" or "generic_v3_multiline" or "generic_v3_multiline_float":
        {
            var list = RrdList(php);
            if (list is null || list.Count < 2)
            {
                return null;
            }

            // generic_multi: series drawn upside down go after the rest in the legend.
            if (template == "generic_multi" && list.Any(s => s.Inverted))
            {
                legendInOrder = false;
                list = list.Where(s => !s.Inverted).Concat(list.Where(s => s.Inverted)).ToList();
            }

            var palette = palettes.GetValueOrDefault(colours);
            var iter = 0;
            var result = new List<(string, string?)>();
            foreach (var item in list)
            {
                var colour = item.Colour;
                if (colour is null && palette is { Length: > 0 })
                {
                    if (iter >= palette.Length)
                    {
                        iter = 0;
                    }

                    colour = palette[iter++];
                }

                result.Add((item.Name, colour));
            }

            return result;
        }

        case "generic_stats":
        {
            var descr = Regex.Match(php, @"\$descr\s*=\s*'([^'$]+)'").Groups[1].Value;
            if (descr.Length == 0)
            {
                return null;
            }

            var palette = palettes.GetValueOrDefault(colours.Length > 0 ? colours : "rainbow_stats_purple");
            if (palette is not { Length: > 0 })
            {
                return null;
            }

            string Colour(int i) => palette[i % palette.Length];
            var main = Regex.Match(php, @"\$colour\s*=\s*'([0-9A-Fa-f]{6})'").Groups[1].Value;

            // generic_stats.inc.php: the series' own colour, then 25th, 50th,
            // 75th percentiles, 1 hour, 1 day and 1 week averages, each the
            // palette's next colour; which of them are drawn depends on the
            // time range, so these are matched by colour, not position.
            legendInOrder = false;
            var iter = main.Length > 0 ? 0 : 1;
            return
            [
                (descr, main.Length > 0 ? main : Colour(0)),
                ("25th percentile", Colour(iter)),
                ("50th percentile", Colour(iter + 1)),
                ("75th percentile", Colour(iter + 2)),
                ("1 hour average", Colour(iter + 3)),
                ("1 day average", Colour(iter + 4)),
                ("1 week average", Colour(iter + 5)),
            ];
        }

        case "generic_duplex":
        {
            var inText = Regex.Match(php, @"\$in_text\s*=\s*'([^'$]+)'").Groups[1].Value;
            var outText = Regex.Match(php, @"\$out_text\s*=\s*'([^'$]+)'").Groups[1].Value;
            var inColour = Regex.Match(php, @"\$colour_line_in\s*=\s*'([0-9A-Fa-f]{6})'").Groups[1].Value;
            var outColour = Regex.Match(php, @"\$colour_line_out\s*=\s*'([0-9A-Fa-f]{6})'").Groups[1].Value;
            return
            [
                (inText.Length > 0 ? inText.Trim() : "In", inColour.Length > 0 ? inColour : null),
                (outText.Length > 0 ? outText.Trim() : "Out", outColour.Length > 0 ? outColour : null),
            ];
        }

        case "":
            return LiteralSeries(php);

        default:
            return null;
    }
}

// Graphs built straight from rrdtool options: every LINE/AREA/HRULE with a
// literal colour and label, in order. Any with a variable colour or label
// would make the order unreliable, so those graphs are left out.
List<(string Name, string? Colour)>? LiteralSeries(string php)
{
    var drawn = Regex.Matches(php, @"(?<q>['""])(?<kind>LINE[0-9.]*|AREA|HRULE|STACK):(?<body>[^'""]*)\k<q>");
    if (drawn.Count == 0 || php.Contains("foreach", StringComparison.Ordinal))
    {
        return null;
    }

    var result = new List<(string, string?)>();
    foreach (Match m in drawn)
    {
        var body = m.Groups["body"].Value;
        if (m.Groups["q"].Value == "\"" && body.Contains('$', StringComparison.Ordinal))
        {
            return null;
        }

        var parts = body.Split(':');
        if (parts.Length < 2)
        {
            continue;
        }

        var hash = parts[0].IndexOf('#', StringComparison.Ordinal);
        if (hash < 0)
        {
            continue;
        }

        var colour = parts[0][(hash + 1)..];
        var label = Unescape(parts[1]);
        if (label.Length == 0)
        {
            continue;
        }

        if (!Regex.IsMatch(colour, "^[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$"))
        {
            return null;
        }

        result.Add((label, colour[..6]));
    }

    return result.Count > 1 ? result : null;
}

// The series a generic_multi* graph is given in $rrd_list, in order.
List<(string Name, string? Colour, bool Inverted)>? RrdList(string php)
{
    // foreach ($stats as $stat) { ... ['descr'] = str_replace('prefix', '', $stat) / $stat / ucfirst($stat)
    var loop = Regex.Match(php, @"\$(?<list>\w+)\s*=\s*\[(?<items>[^\]]*)\];(?<rest>[\s\S]*?)foreach\s*\(\s*\$\k<list>\s+as\s+\$(?<var>\w+)\s*\)");
    if (loop.Success)
    {
        var keys = Regex.Matches(loop.Groups["items"].Value, @"'([^']+)'").Select(m => m.Groups[1].Value).ToList();
        var v = loop.Groups["var"].Value;
        var descr = Regex.Match(php, $@"\['descr'\]\s*=\s*(?<expr>[^;]+);");
        if (keys.Count > 0 && descr.Success)
        {
            var expr = descr.Groups["expr"].Value.Trim();
            Func<string, string>? name = null;
            if (expr == "$" + v)
            {
                name = k => k;
            }
            else if (Regex.Match(expr, $@"^str_replace\('([^']*)',\s*'([^']*)',\s*\${v}\)$") is { Success: true } sr)
            {
                name = k => k.Replace(sr.Groups[1].Value, sr.Groups[2].Value, StringComparison.Ordinal);
            }
            else if (expr == $"ucfirst(${v})")
            {
                name = k => char.ToUpperInvariant(k[0]) + k[1..];
            }

            if (name is not null)
            {
                var invertRule = Regex.Match(php, @"if\s*\((?<cond>[^{]*)\)\s*\{\s*\$rrd_list\[\$i\]\['invert'\]\s*=\s*true");
                return keys.Select(k => (name(k), (string?)null, invertRule.Success && Inverted(invertRule.Groups["cond"].Value, v, k))).ToList();
            }
        }

        return null;
    }

    // 'key' => ['descr' => 'Name', 'colour' => 'RRGGBB'], ...
    var arrayItems = Regex.Matches(php, @"\[\s*'descr'\s*=>\s*'(?<descr>[^']+)'(?<more>[^\]]*)\]");
    if (arrayItems.Count > 1 && !php.Contains("$rrd_list[$i]['descr'] = $", StringComparison.Ordinal))
    {
        return arrayItems.Select(m =>
        {
            var colour = Regex.Match(m.Groups["more"].Value, @"'colour'\s*=>\s*'([0-9A-Fa-f]{6})'").Groups[1].Value;
            var inverted = Regex.IsMatch(m.Groups["more"].Value, @"'invert'\s*=>\s*(true|1)");
            return (m.Groups["descr"].Value.Trim(), colour.Length > 0 ? colour : (string?)null, inverted);
        }).ToList();
    }

    // $rrd_list[$i]['descr'] = 'Name'; ... one after another.
    var literal = Regex.Matches(php, @"\$rrd_list\[[^\]]+\]\['descr'\]\s*=\s*'(?<descr>[^']+)'");
    if (literal.Count > 1 && !php.Contains("foreach", StringComparison.Ordinal))
    {
        return literal.Select(m => (m.Groups["descr"].Value.Trim(), (string?)null, false)).ToList();
    }

    return null;
}

static bool Inverted(string condition, string variable, string key)
{
    // str_contains($stat, 'Out') || str_contains($stat, 'Retrans') ...
    var tests = Regex.Matches(condition, $@"str_contains\(\${variable},\s*'([^']+)'\)");
    return tests.Count > 0 && tests.Any(t => key.Contains(t.Groups[1].Value, StringComparison.Ordinal));
}

static string Unescape(string label) => label.Replace("\\\\n", string.Empty, StringComparison.Ordinal).Replace("\\n", string.Empty, StringComparison.Ordinal)
    .Replace("\\\\l", string.Empty, StringComparison.Ordinal).Replace("\\l", string.Empty, StringComparison.Ordinal)
    .Replace("\\:", ":", StringComparison.Ordinal).Replace("_", " ", StringComparison.Ordinal).Trim();

static string Escape(string s) => s.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
